spring.application.name=algafood-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yasmin}

# Habilita a geração automática do DDL - Data Definition Language (Linguagem de Definição de Dados)
# O Hibernate gera automaticamente o DDL baseado nas entidades (CREATE, ALTER, DROP).
#spring.jpa.generate-ddl=true 

# Define o que o Hibernate fará com o schema do banco ao iniciar a aplicação.
# create = apaga tudo e cria todas as tabelas novamente sempre que a aplicação sobe.
#spring.jpa.hibernate.ddl-auto=create

# Faz o Hibernate imprimir no console todos os SQL que ele executa.
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration,classpath:db/testdata

# Configurações para desenvolvimento
spring.devtools.restart.enabled=true

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql

#Habilitando erros na desserialização de propriedades inexistentes ou ignoradas
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

#habilitando lower camel case
spring.jackson.property-naming-strategy=SNAKE_CASE
